version: '3'
services:
  danimai:
    env_file:
      - .env
    build: .
    container_name: ${APP_SLUG}_app
    volumes:
      - .:/src/usr/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - danimai_network
    depends_on:
      - postgres
    command: npm run start:dev

  postgres:
    container_name: ${APP_SLUG}_postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    networks:
      - danimai_network
    ports:
      - ${DATABASE_PORT}:5432
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${DATABASE_NAME},${TEST_DATABASE_NAME}

networks:
  danimai_network:
    driver: bridge
